### PR TITLE
Added interfaces for all entities

### PR DESCRIPTION
**Pull request by LazyTarget**

### CODE REVIEW

**Comment by ThanosSiopoudis** [comment]
Hi @LazyTarget, thanks for the PR. Unfortunately it fails in Travis, if you can please fix it I'll be happy to merge.

**Comment by LazyTarget** [comment]
The build failure is now resolved

**Comment by v1n1akabozo** [comment]
Just wondering why adding interfaces to entities?

**Comment by LazyTarget** [comment]
Because all of them derive from BaseObject. With members I simply don't care about. Also I belive these members not have public setters

**Pull request merged**
