### PR TITLE
Player now inherits from Person and  new offsets.

### PR DESCRIPTION
**Pull request by joshlatimer**
Player now inherits from Person to simplify the codebase and some new offsets
for 15..3.2 added.

### CODE REVIEW

**Comment by ThanosSiopoudis** [comment]
Thanks for the PR @joshlatimer 
I see that you've restructured the Player object. While having a Person base object is a good idea, unfortunately it won't work with other operating systems. I've noticed over time, that the changes across them are not always consistent, and adds a lot of overhead maintaining them.

In general, I like to keep offsets within the structure confines. It's easier to track changes when you know where an object starts and where it ends, without having to calculate "virtual" structures within them, especially when we have to deal with 3 different operating systems.

Could you please change the PR to just assign the new FM2015 offsets with the current structure?

**Comment by joshlatimer** [comment]
Are you sure it wont work for other operating systems? It gets the Person's Memory Address by adding  the Version.PlayerOffsets.Player to the player's address, so we could still have 1 version class with a different PersonOffset for each operating system for each game version and it should work fine right? maybe I'm wrong!  I don't have another operating system to test with.

I understand what you're saying, I just think this makes things way easier to understand and will mean less work getting new offsets for each new version. For example the Player's ID is always at 0x08 yet PlayerOffsets.ID is just a cluster fuck due to how things are currently done.

**Comment by ThanosSiopoudis** [comment]
The problem is when you start trying to assign the "Person" parent object to the rest of the People types, you will end up having the need for different offsets. In essence, the only common offsets for Players, Staff, PlayerNonPlayers, Referees, etc. are RowID, UID, UID2. Nothing else is shared, therefore it doesn't make sense having a main object just for these three. You will still need to differentiate.

I understand that it looks more neat, when you take a look at just one object, like Players, but if you try to expand you'll see what I mean. It is also, probably, the same way the game itself is implemented internally, but in the memory, it just complicates things terribly.

**Comment by joshlatimer** [comment]
I looked into it and the common offsets are DOB, Contract info, UID, RowID, Name and Team/Club info for Staff&Player. I don't know what PlayerNonPlayers is, but a Referee has a lot less game data so it's fine for that to not inherit Person once implemented I guess.

The only thing this really changes is that certain properties  are retrieved a different way which makes more sense, but the player's memory address hasn't changed at all. I think this makes things a bit easier to understand and maintain but maybe I'm wrong, you know more than me!  let me know, I'll revert tomorrow if you don't think this is a good idea!

**Comment by ThanosSiopoudis** [comment]
PlayerNonPlayer is a person who is both a Player and Staff. But if you say that this applies for all of them, I guess it applies for them, too.

Ok, we'll go with your structure, but I'd really appreciate it if you could revert the part about the Playing attributes, as I don't think there's a reason to separate them from the rest of the properties in the object.

Once you do this, I'll merge your PR

**Comment by joshlatimer** [comment]
Oh I didn't realise that's how playing attributes works, I've fixed it now.

**Comment by ThanosSiopoudis** [comment]
Great, thanks! If you can resolve conflicts in your fork by merging to master, I'll merge the PR. Thanks

**Comment by joshlatimer** [comment]
I think I've done that now :)

**Pull request merged**
