### PR TITLE
Fixed nations, club wage budget, contract bonuses

### PR DESCRIPTION
**Pull request by joshlatimer**
Fixed Nations
Fixed Person.Club
Fixed issue with ProcessManager.ReadString extra pointer
Fixed club wage budget
Fixed contract bonuses & clauses
Fixed indentation of some files

### CODE REVIEW

**Comment by joshlatimer** [comment]
Not really what sure to do about the indentation, my IDE (Visual Studio 2015) automatically uses tabs instead of spaces, but a lot of files in the repository right now use spaces. This makes my commits look really messy and insane, I'm not sure if we should change the repository to use tabs instead of spaces or if I should change my Visual Studio settings?

**Comment by ThanosSiopoudis** [comment]
Hi @joshlatimer 
to change the indentation mode for VS, go to:
Tools > Options... > Text Editor > All Languages > Tabs
or if you want specifically for C#
Tools > Options... > Text Editor > C# > Tabs  
then, enter:
`Tab Size: 4`
`Indent size: 4`
- [x] Insert spaces
- [ ] Keep tabs  

Furthermore, the automated build failed, so please take a look at that, too (click on the little x next to the commit hash)

**Comment by tthordarson** [comment]
Well done, sir!

**Comment by joshlatimer** [comment]
That's done thanks, so is there anyway I can undo all the indentation changes?  or should I just delete this pull request and redo the changes to the actual framework? or maybe I should just fix the indentation in the files I've already changed with this pull request? because for example some files like https://github.com/ThanosSiopoudis/FMScoutFramework/blob/master/Entities/Ingame/ClubFinances.cs have screwed up indentation at the moment. 

Lemme know what you think is best!

**Comment by ThanosSiopoudis** [comment]
I haven't tried it myself, but apparently you can automatically convert tabs to spaces in VS by doing the following:
1. Select the text whose white space you want to convert from tabs to spaces
2. In Edit > Advanced, click Untabify Selection

Please try this first, and if it fails, I'm afraid you'll have to make another pull request. All three OSes have different tab widths, and the only way to keep the code consistent across all of them are spaces.

After you're done with this, I have a couple of questions regarding the PR :)
Thanks

**Pull request closed without merging**
